# whowasi: a tool to record source version information into binaries.
#
# Copyright (c) 2026 Institut des Géosciences de l'Environnement, Grenoble.
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).

import argparse
import os

from ._ignore import IgnoreRuleSet
from ._utils import detailed_git_status, write_line_c, write_line_f90

# Command-line arguments

parser = argparse.ArgumentParser(
    prog="whowasi",
    description="Record source version information into binaries.",
    epilog="This programme is released under the BSD-3-Clause license.",
    formatter_class=argparse.RawDescriptionHelpFormatter,
)

parser.add_argument(
    "-r",
    "--repository",
    help="Path to the repository (absolute or relative to current directory)",
    default=os.getcwd(),
)
parser.add_argument(
    "-c",
    "--version-control",
    help="Version control system used by the repository.",
    choices=("git",),
    default="git",
)
parser.add_argument(
    "-l",
    "--language",
    help="Programming language to use (case-insensitive).",
    choices=("C", "c", "F90", "f90"),
    required=True,
)
parser.add_argument(
    "-o",
    "--output",
    help=(
        "Output file where to write the code. A relative path is interpreted "
        "as relative to the root of given repository, not relative to current "
        "directory (default=whowasi.*)."
    ),
    default=None,
)
parser.add_argument(
    "-n",
    "--name",
    help="Name of the whowasi function",
    default="whowasi",
)
parser.add_argument(
    "-i",
    "--ignore",
    help="Rules to ignore certain files. See documentation for valid syntax.",
    required=False,
    nargs="+",
    default=[],
)
parser.add_argument(
    "--no-auto-ignore",
    help="Disable default ignore rules.",
    action="store_true",
)
parser.add_argument(
    "--f90-module-name",
    help=(
        "Name of the module when generating FORTRAN 90+ code. "
        "This option has no effect with other languages."
    ),
    default=None,
)
parser.add_argument(
    "-f",
    "--report-format",
    help="Format of the whowasi report.",
    choices=("simple", "pretty"),
    default="simple",
)
args = parser.parse_args()

language = args.language.lower()
vcs = args.version_control
output_file = args.output
if output_file is None:
    extensions = {"c": "c", "f90": "f90"}
    output_file = f"whowasi.{extensions[language]}"
routine_name = args.name
ignore = [rule for rule in args.ignore]
if args.f90_module_name is not None:
    module_name = args.f90_module_name
else:
    module_name = f"module_{args.name}"

# Get revision information

if not args.no_auto_ignore:
    if language == "c":
        ignore += [f"**/{args.name}.{ext}" for ext in "cho"]
    elif language == "f90":
        ignore += [f"**/{args.name}.f90", f"**/module_{args.name}.mod"]
    else:
        msg = "f{language} language."
        raise NotImplementedError(msg)
if vcs == "git":
    status = detailed_git_status(args.repository, ignore=IgnoreRuleSet(ignore))
else:
    msg = f"Version control system: f{vcs}"
    raise NotImplementedError(msg)

# Format revision information

if  args.report_format == "simple":
    lines = ["", ">>> Beginning of whowasi report <<<", ""] \
        + status \
        + ["", ">>> End of whowasi report <<<", ""]
elif args.report_format == "pretty":
    lines = ["", "?? whowasi ??", ""] + status + [""]
    nmax = max(len(line) for line in lines)
    full_line = "#" * (nmax + 4)
    lines = (
        [full_line]
        + [f"# {line}" + " " * (nmax - len(line)) + " #" for line in lines]
        + [full_line]
    )
else:
    msg = f"Unknown format for whowasi report: {args.report_format}."
    raise ValueError(msg)

# Hard-coded values

header = "Code generated by whowasi (https://github.com/lucas-ige/whowasi)."

# Create the library

if language == "c":
    if not output_file.endswith(".c"):
        msg = "Unexpected file extension."
        raise ValueError(msg)

    with open(f"{output_file[:-2]}.h", mode="w") as f:
        f.write(f"/* {header} */\n\n")
        f.write(f"void {args.name}(FILE *stream);\n")

    with open(output_file, mode="w") as f:
        f.write(f"/* {header} */\n\n")
        f.write("#include <stdio.h>\n\n")
        f.write(f"void {args.name}(FILE *stream)")
        f.write(" {\n")
        f.writelines(f"    {write_line_c(line)};\n" for line in lines)
        f.write("}\n")

elif language == "f90":
    with open(output_file, mode="w") as f:
        f.write(f"! {header} \n\n")
        f.write(f"module {module_name}\n\n")
        f.write("  implicit none\n\n")
        f.write("contains\n\n")
        f.write(f"  subroutine {args.name}(unit)\n")
        f.write("    integer, intent(in) :: unit\n")
        f.writelines(f"    {write_line_f90(line)}\n" for line in lines)
        f.write(f"  end subroutine {args.name}\n\n")
        f.write(f"end module {module_name}\n")

else:
    msg = "f{language} language."
    raise NotImplementedError(msg)
